language: php

php:
  - 7.1
  - 7.2

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover